CosmosTUe/Cosmos

- .github/workflows/deploy.yml
- .github/workflows/dev-deploy.yml
Fixed deploy workflows per Bart's request
> Fix deploy and dev-deploy workflows

- cosmos/forms/profile.py
- requirements.txt
@maximekabel pls check over whether the comments adequately explain the purposes of the classes made.
> Document models

- cosmos_cms/templates/cms/image_text_card.html
Made content text `safe` and added padding to text to make it look better
> Text+img add padding

- cosmos/migrations/0001_init_models.py
- cosmos/migrations/0003_profile_terms_newsletter_fields.py
- cosmos/migrations/0004_board_commitee_blank_array.py
- cosmos/models/board.py
- cosmos/models/committee.py
- cosmos/static/cosmos/css/core.css
- cosmos/static/cosmos/css/registration.css
- cosmos/templates/base.html
- cosmos/templates/fullwidth.html
- cosmos_cms/models.py
- cosmos_cms/templates/cms/committee_list.html
- cosmos_cms/templates/cms/contacts/contact.html
- cosmos_cms/templates/cms/image_text_card.html
- legacy/migrations/0001_initial.py
- tests/user/views.py
Made some changes to base.html core.css and the template for the text+img card
> Beautify base

- cosmos/migrations/0005_group_display_name.py
- cosmos/models/board.py
- cosmos/models/committee.py
- cosmos/settings.py
- cosmos_cms/cms_plugins.py
- cosmos_cms/models.py
Secure cookies
Secure referrer policy
Most other things will have to be setup in nginx
> Basic security setting

- apps/cms_plugins/apps.py
- apps/cms_plugins/models.py
- apps/legacy/admin.py
- apps/legacy/legacy_router.py
- apps/legacy/mail.py
- apps/legacy/models.py
- apps/legacy/tasks.py
- apps/legacy/tokens.py
- apps/legacy/views.py
remove unnecessary property explanations
remove unnecessary django app explanations
> Document legacy app

- .gitignore
- cosmos/settings.py
- secret_settings.py
- tests/secrets.json.template
self-explanatory
keep track of errors
run to see if output on console is replicated on the log file
> Save logs to file

- apps/users/admin/profile.py
Add more columns to profile list in the admin page.
Adds department, program, nationality, terms_confirmed, subscribed_newsletter to the list of profile on the admin page.
Allows easy checking if the profiles are valid.
Manually.
> Add more columns to profile admin page

- apps/users/views.py
- tests/user/views.py
Fix creation of users with invalid profile forms.
User was created without checking if the profile form is valid.
Fixes a bug
Manually by registering with a invalid profile form.
> Fix user creation without valid profile

- cosmos/settings.py
- requirements.txt
Added bootstrap support again
it broke the website
> Add bootstrap

- apps/users/admin/profile.py
- apps/users/sendgrid.py
> Hotfix sendgrid contact syncing

- apps/users/forms/profile.py
- apps/users/models/user/profile.py
- apps/users/sendgrid.py
- tests/user/__init__.py
Fix preferences, specifically email settings, not being saved when changed in profile.
Form fields defaulted to required, therefore other fields not on the page were causing issues
Solves bug.
Manually.
> Fix preferences not being updated in profile

- requirements.txt
The newest version contains my patch which allows pickling of errors.
Up the minimum version of python-http-client to contain the patched version.
Allows us to use celery with sendgrid.
Test case in sendgrid-http-client repo.
> Require patched version of python-http-client

- apps/users/stats.py
Rotates xticks to make nice stats
> Rotate xticks 45deg

- cosmos/settings.py
remove legacy database in settings
> Remove reference to legacy database

- requirements.txt
security alert about CVEs in current version
See security tab of repository.
> Upgrade django version

- cosmos/templates/footer.html
- cosmos/templates/privacy.html
- cosmos/templates/terms.html
- cosmos/urls.py
- cosmos/views.py
* Add terms and conditions page
* Add (empty) privacy policy page
> Add links to footer

- cosmos/templates/navbar.html
> Add logout button

- cosmos/templates/navbar.html
Was changed in #138, but not noticed during all the merging
> Fix logout url reverse

- apps/users/templates/user/profile.html
> Fix missing form tags in profile

- cosmos/views.py
Now returns the correct status code instead of just 200
> Fix error page status code

- apps/users/static/cosmos_users/css/auth.css
- cosmos/forms.py
- cosmos/models.py
- cosmos/templates/gmm/gmm_confirm_delete.html
- cosmos/templates/gmm/gmm_create.html
- cosmos/templates/gmm/gmm_update.html
- cosmos/templates/news/news_confirm_delete.html
- cosmos/templates/news/news_create.html
- cosmos/templates/news/news_update.html
- cosmos/templates/photo_album/photo_album_add_photos.html
- cosmos/templates/photo_album/photo_album_confirm_delete.html
- cosmos/templates/photo_album/photo_album_create.html
- cosmos/templates/photo_album/photo_album_list.html
- cosmos/templates/photo_album/photo_object_confirm_delete.html
- cosmos/views.py
Cleans up forms, making them readable and conform to the same style as the login/registration forms.
> Cleaner forms

- cosmos/templates/index.html
> Remove events on homepage

- cosmos/templates/gmm/gmm_list.html
Footer is now sticky to the bottom of the page
div tag was placed outside of content block
Fixes issue #172
> Footer is now sticky to the bottom of the page

- cosmos/views.py
> Fix photos list error

- apps/users/admin/institutions.py
- apps/users/admin/profile.py
- apps/users/stats.py
- tests/user/admin/__init__.py
- tests/user/admin/institutions.py
- tests/user/admin/profile.py
get stats button no longer worked on the profile page due to a change in user model
Removed the program/department stat on the "Profile" page and moved it to the TU/e institution page
fixes issue #151 
- [ -] Bug fix (non-breaking change which fixes an issue)
> Added stats button to institution page

- cosmos/templates/resources.html
> Remove policy documents button

- apps/users/helper_functions.py
- tests/user/forms/registration.py
- tests/user/views/profile.py
- tests/user/views/registration.py
> Temporarily remove fontys support

- cosmos/templates/about.html
> Fix about us page text

- cosmos/static/cosmos/css/core.css
- cosmos/templates/index.html
> Fix homepage stats on mobile

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
- .github/pull_request_template.md
> Simplify github templates

- requirements.txt
Changes have now been published to a new version, so git version is no longer needed.
Fixes #
> Change crispy-bootstrap requirement to normal package

- cosmos/templates/navbar.html
- tests/cosmos/views/__init__.py
- tests/cosmos/views/index.py
- tests/secrets.json.template
Wrote tests for the CR door center
> door sensor tests

- cosmos/templates/navbar.html
- cosmos/views.py
Patch to store the status of the CR door with a file instead of a global variable
> Use file to store door status

- .github/workflows/test.yml
- Pipfile
- Pipfile.lock
- cosmos/settings.py
- secrets.json.template
Add configuration for Redis-based cache and celery backend
> Add configurable Redis based cache and celery backend

- Pipfile
- Pipfile.lock
- apps/events/models.py
- apps/events/templates/events/event_view.html
- apps/events/templates/events/events_archive.html
- apps/events/urls.py
- apps/events/views.py
- cosmos/settings.py
Add an ICal feed for events + hide past events on the events list.
Feature was requested by Tudor Popescu
Fixes #
> Add ICal calendar feed for events + Hide past events

- Pipfile
- Pipfile.lock
Not needed as actions run isort itself, and it causes problems too often
> Remove flak8-isort

- tests/events/views/events.py
The Isort test stopped working, this should fix it
> Fixed Isort issue for test

- .github/workflows/format.yml
- .github/workflows/lint.yml
- .github/workflows/test.yml
- .pre-commit-config.yaml
- Pipfile
- Pipfile.lock
Django 4.0 got released and will break stuff, this forces Django to stay on 3.X
Python version was set to 3.9, but that isn't the Ubuntu repos yet
Pre-commit was added to dev packages
> Changed Python version to 3.8 and forced Django <4 + pre-commit

- Pipfile.lock
- apps/users/templates/committees/overview.html
- apps/users/templates/committees/subpage.html
> Thumbnail committee photos as PNG as they have transparent backgrounds

- .github/workflows/pipenv.yml
Missed install for pipenv itself
> Fix pipenv update github action

- apps/async_requests/newsletter/sendgrid_service.py
- fix bracket closures in `is_subscribed()` string
> Fix sendgrid 400 error

- apps/core/templates/merch.html
- apps/core/templates/navbar.html
- apps/core/urls.py
- apps/core/views/core.py
> Add merch store

- apps/core/static/cosmos/js/gmm.js
- apps/core/static/cosmos/js/photos.js
Image urls were changed due to thumbnail generation, breaking the js code. Now it uses the url in the data attribute.
Fixes #304
> Fix photo album prev/next buttons

- apps/core/templates/resources.html
> Add member's initiative section

- apps/events/views.py
> Change order of event archive

- apps/events/static/cosmos_events/css/carousel.css
- apps/events/templates/events/event_carousel.html
- apps/events/urls.py
- apps/events/views.py
- cosmos/settings.py
> Implement event + news carousel

- .github/workflows/test.yml
Fixes test CI, which breaks due to the environment variable interfering with pipenv. As this is variable is no longer needed for the secret settings configuration, I've removed it.
> Remove env variable from test CI

- apps/core/templates/internal/internal_list.html
Add message to login on the internal documents page when not logged in.
> Add message to internal docs page when not logged in

- apps/core/templates/resources.html
> Add reimbursement form

- apps/events/templates/events/event_carousel.html
Makes images in carousel be centered. Vertical images look strange otherwise.
> Fix carousel image centering

- apps/users/templates/user/activate.html
Fixes issue with account activation page not working.
> Add missing csrf token to account activation

- Pipfile.lock
- apps/events/templates/events/event_carousel.html
- apps/users/templates/user/activate.html
> Merge to master

- apps/users/templates/user/mail_confirmation.html
Uses bootstrap email for a nicer and more consistent template
> Update confirmation email template

- apps/core/views/photos.py
> Added missing cosmos_core to reverse

- apps/events/views.py
Cant access current site if running first migration ever, not sure why this code needs to be run though when migrating, but that is a django problem
> Fix migration error on clean database

- apps/core/templates/resources.html
Changed the Members' Initiative link to the one Kali gave me. I tested it with my TUe and Fontys accounts, and only the TUe one worked, which means that the current link works as intended.
Fixes #
- [ x] Bug fix (non-breaking change which fixes an issue)
- [x ] All new code is fully covered by tests (see coverage report)
> [Fix] Changed Member's Initiative Link

- apps/core/templates/footer.html
Board member Maco asked us to update the footer to the new phone number of Cosmos. 
Fixes #
> Change footer phone number to new Cosmos phone number

- cosmos/settings.py
- secrets.json.template
Remove some options not actually used anymore, and replace them with more sensible options.
> Remove outdated secrets entries

- apps/core/templates/index.html
- apps/core/views/core.py
- Fixes news not being visible
- Adds events to index page
- Add heading for partners section
> Miscellaneous fixes for index page

- apps/core/templates/index.html
- Rotates through partners on mobile
- Makes carousel controls visible
- Makes carousel controls work
> Fix partner carousel

- Pipfile
- Pipfile.lock
> Merge django newsletter fix to master

- apps/async_requests/newsletter/newsletter_service.py
> Fix newsletter sync

- .pre-commit-config.yaml
Bump isort version in pre-commit config from 5.10.1 to 5.12.0
> Bump isort from 5.10.1 to 5.12.0

- apps/core/templates/index.html
- apps/core/templates/news/news_list.html
- apps/users/templates/user/profile.html
- apps/users/urls.py
- apps/users/views.py
Add a card to the news page which redirects to the newsletter signup in the profile page.
> Add newsletter redirect button

- apps/core/templates/navbar.html
- apps/core/views/photos.py
- tests/cosmos/views/photo_view.py
As requested by board, now requires logging in to view
> Make photos section private

- apps/users/views.py
since SendGrid is no longer free and for now we cannot switch to another API
Fixes #
> disabled account e-mail confirmation

- apps/users/admin/profile.py
- apps/users/models/profile.py
- apps/users/stats.py
as well as distribution of bachelor/master/exchange and eea/non-eea students. this is in place of the nationality stats button. but that old code is still kept. also 'tmp' folder where graph jpg was kept was changed to 'temp' since windows didn't like that, shouldn't be an issue
Fixes #
> implemented getting stats for academic year joined

- .gitignore
- secret_settings.py
Added MacOS compatibility to secret_settings.py, and updated .gitignore to exclude MacOS specific files.
> Update .gitignore and secret_settings.py for macOS compatibility
